
package wsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://localhost:9999/ws/hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/queryByNameRequest", output = "http://localhost:9999/ws/hello/HelloWorld/queryByNameResponse")
    public String queryByName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/queryByIDRequest", output = "http://localhost:9999/ws/hello/HelloWorld/queryByIDResponse")
    public String queryByID(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/addRequest", output = "http://localhost:9999/ws/hello/HelloWorld/addResponse")
    public boolean add(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/updateRequest", output = "http://localhost:9999/ws/hello/HelloWorld/updateResponse")
    public void update();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/deleteRequest", output = "http://localhost:9999/ws/hello/HelloWorld/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://localhost:9999/ws/hello/HelloWorld/showRequest", output = "http://localhost:9999/ws/hello/HelloWorld/showResponse")
    public String show();

}
